name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: SSH
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/app/invitation-backend
            cd ~/app/invitation-backend
            git pull origin master
            git status
            go get .
            go build
            kill $(lsof -t -i:8080)
            ./main