name: cd

on:
  push:
    branches:
      - masterss

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: SSH
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/app/invitation-backend
            cd ~/app/invitation-backend
            git init
            git clone https://github.com/Harits19/invitation-backend-service.git .
            git remote add origin https://github.com/Harits19/invitation-backend-service.git
            git branch --set-upstream-to=origin/master master
            git pull origin master
            git status
            # docker build -t invitation-backend-image .
            # docker container stop invitation-backend-container
            # docker container rm invitation-backend-container
            # docker container ls
            # docker container create --name invitation-backend-container -e PORT=8080 -e INSTANCE_ID="invitation-backend-instance" -p 8080:8080 --restart always invitation-backend-image
            # docker container start invitation-backend-container
            # docker container ls
            # sudo ufw allow 8080
