name: cd

on:
  push:
    branches:
      - init

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: SSH
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            install go
            update go path
            install docker
            install docker compose
            run docker compose
            go install github.com/cosmtrek/air@latest

            mkdir -p ~/app/invitation-backend
            cd ~/app/invitation-backend
            git init
            git clone https://github.com/Harits19/invitation-backend-service.git
            git pull origin master
            git status
            go get .
            go build